### ISSUE TITLE
Add link to software packages

### ISSUE THREAD

**Issue by marklhc** [mmm-usc/mmmlab_website#10]
e.g., `R2spa`; `unbiasr`; `pinsearch`

**Comment by meltemozcan** [comment]
PartInv Shiny -> unbiasr

**Comment by meltemozcan** [comment]
_site.yml add links for R2spa, pinsearch

**Comment by meltemozcan** [comment]
https://github.com/marklhc/pinsearchv

**Comment by marklhc** [comment]
https://github.com/Gengrui-Zhang/R2spa/

**Comment by meltemozcan** [comment]
https://github.com/winniewytse/hcbr "HCBR R package"
